### ISSUE TITLE
adapt deploy error `project file index.tsx does not exist`

### ISSUE THREAD

**Issue by Wkasel** [gosignal/dineforward#25]
```shell
# from inside project root
adapt run --deployID df-local-deploy local-dev
Adapt by Unbounded Systems [CLI v0.1.0]

  ✖ Installing node modules
    → Project file 'index.tsx' does not exist
    Validating project
    Creating new project deployment
 ›   Error: Project file 'index.tsx' does not exist
```

**Comment by mvachhar** [comment]
Change into the adapt directory and repeat the command. Don't forget to set DOTENV for Cloudinary and other services.

**Comment by mterrel** [comment]
@mvachhar We might want to update the README to include the need to be in the `adapt` directory.

**Comment by mvachhar** [comment]
README updated in PR #26

**Comment by mvachhar** [comment]
Did this resolve the issue, can I close this?

**Comment by Wkasel** [comment]
@mvachhar I haven't had a moment to test it, but go ahead and close.
